; When hosting your own service:
;baseUrl = 'http://127.0.0.1:8000'

; As an alternative, a shared service will be available soon (no details available yet, IP whitelisting will be required)
;baseUrl = 'https://???'

;Useful when NOT hosting your own service
; Blacklist/Whitelist entries will be compared against FEED and NAME headers in the provided BEACON files.

; If a whitelist is defined, sources from your whitelist will be shown ONLY
;whitelist[] =

; If a blacklist is defined, all sources will be shown, EXCEPT the ones on the blacklist.
; (It usually does not make sense to use both black and whitelist at the same time.)
;blacklist[] =
