<p><b>BEACONfinder</b></p>
<?php $result = $this->BEACONfinder->getByAuthorityId($this->authorityId); ?>
<?php if (!$result || count($result) == 0): ?>
  <p>Not found</p>
<?php else: ?>
  <ul>
    <?php foreach ($result as $item): ?>
      <li>
        <?php if (!empty($item->getNAME()) && !empty($item->getTargetUri())): ?>
          <a href="<?=$item->getTargetUri()?>" target="_blank"><?=htmlspecialchars($item->getNAME())?></a>
        <?php else: ?>
          <?=$item->getBeaconUri()?>
        <?php endif; ?>
      </li>
    <?php endforeach; ?>
  </ul>
<?php endif; ?>
